[2024-07-01T22:57:11.621+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:57:11.622+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T22:57:11.625+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:57:11.625+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:57:11.656+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:57:11.649+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T22:57:11.659+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:57:11.711+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.102 seconds
[2024-07-01T22:57:42.117+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:57:42.119+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T22:57:42.122+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:57:42.121+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:57:42.157+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:57:42.147+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T22:57:42.160+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:57:42.219+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.120 seconds
[2024-07-01T22:58:13.154+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:58:13.156+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T22:58:13.159+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:58:13.158+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:58:13.198+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:58:13.189+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T22:58:13.202+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:58:13.255+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.112 seconds
[2024-07-01T22:58:43.408+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:58:43.409+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T22:58:43.412+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:58:43.412+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:58:43.439+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:58:43.433+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T22:58:43.441+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:58:43.499+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.098 seconds
[2024-07-01T22:59:13.642+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:59:13.644+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T22:59:13.648+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:59:13.647+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:59:13.688+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:59:13.680+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T22:59:13.691+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:59:13.783+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.153 seconds
[2024-07-01T22:59:44.077+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:59:44.078+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T22:59:44.081+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:59:44.080+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:59:44.117+0000] {logging_mixin.py:188} INFO - [2024-07-01T22:59:44.109+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T22:59:44.120+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T22:59:44.196+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.128 seconds
[2024-07-01T23:00:15.102+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:00:15.104+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:00:15.108+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:00:15.107+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:00:15.145+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:00:15.136+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:00:15.149+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:00:15.206+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.115 seconds
[2024-07-01T23:00:46.181+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:00:46.183+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:00:46.187+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:00:46.185+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:00:46.240+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:00:46.228+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:00:46.243+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:00:46.313+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.150 seconds
[2024-07-01T23:01:16.793+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:01:16.795+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:01:16.798+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:01:16.797+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:01:16.833+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:01:16.826+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:01:16.836+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:01:16.896+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.113 seconds
[2024-07-01T23:01:47.798+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:01:47.800+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:01:47.803+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:01:47.803+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:01:47.840+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:01:47.832+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:01:47.843+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:01:47.905+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.121 seconds
[2024-07-01T23:02:18.243+0000] {processor.py:161} INFO - Started process (PID=41) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:02:18.244+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:02:18.247+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:02:18.246+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:02:18.281+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:02:18.273+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:02:18.284+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:02:18.351+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.117 seconds
[2024-07-01T23:02:49.465+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:02:49.467+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:02:49.469+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:02:49.469+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:02:49.509+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:02:49.497+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:02:49.514+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:02:49.603+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.148 seconds
[2024-07-01T23:03:19.695+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:03:19.696+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:03:19.699+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:03:19.699+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:03:19.746+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:03:19.735+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:03:19.749+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:03:19.822+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.141 seconds
[2024-07-01T23:03:50.861+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:03:50.863+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:03:50.866+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:03:50.865+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:03:50.900+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:03:50.892+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:03:50.902+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:03:50.962+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.109 seconds
[2024-07-01T23:04:21.963+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:04:21.965+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:04:21.968+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:04:21.967+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:04:22.005+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:04:21.996+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:04:22.008+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:04:22.062+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.107 seconds
[2024-07-01T23:04:53.037+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:04:53.039+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:04:53.042+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:04:53.042+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:04:53.080+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:04:53.071+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:04:53.083+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:04:53.146+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.123 seconds
[2024-07-01T23:05:24.217+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:05:24.219+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:05:24.222+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:05:24.222+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:05:24.257+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:05:24.249+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:05:24.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:05:24.325+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.116 seconds
[2024-07-01T23:05:55.251+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:05:55.252+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:05:55.255+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:05:55.254+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:05:55.299+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:05:55.288+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:05:55.302+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:05:55.377+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.140 seconds
[2024-07-01T23:06:26.338+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:06:26.340+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:06:26.343+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:06:26.342+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:06:26.380+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:06:26.372+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:06:26.382+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:06:26.438+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.109 seconds
[2024-07-01T23:06:57.470+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:06:57.472+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:06:57.477+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:06:57.476+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:06:57.525+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:06:57.514+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:06:57.529+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:06:57.604+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.150 seconds
[2024-07-01T23:07:28.686+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:07:28.689+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:07:28.693+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:07:28.692+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:07:28.734+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:07:28.725+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:07:28.738+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:07:28.806+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.135 seconds
[2024-07-01T23:07:59.737+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:07:59.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:07:59.747+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:07:59.745+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:07:59.806+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:07:59.797+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:07:59.810+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:07:59.882+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.159 seconds
[2024-07-01T23:08:19.457+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:08:19.460+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:08:19.467+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:08:19.464+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:08:19.547+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:08:19.535+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:08:19.551+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:08:19.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.205 seconds
[2024-07-01T23:08:30.853+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:08:30.856+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:08:30.862+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:08:30.861+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:08:30.958+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:08:30.940+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:08:30.962+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:08:31.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.212 seconds
[2024-07-01T23:09:01.737+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:09:01.740+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:09:01.743+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:09:01.742+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:09:01.790+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:09:01.779+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:09:01.794+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:09:01.864+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.140 seconds
[2024-07-01T23:09:31.992+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:09:31.995+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:09:31.999+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:09:31.998+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:09:32.034+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:09:32.027+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:09:32.037+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:09:32.099+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.119 seconds
[2024-07-01T23:10:02.878+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:10:02.879+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:10:02.882+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:10:02.881+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:10:02.912+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:10:02.905+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:10:02.915+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:10:02.973+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.102 seconds
[2024-07-01T23:10:33.443+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:10:33.445+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:10:33.448+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:10:33.447+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:10:33.485+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:10:33.477+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:10:33.489+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:10:33.563+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.129 seconds
[2024-07-01T23:11:03.723+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:11:03.725+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:11:03.727+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:11:03.727+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:11:03.761+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:11:03.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:11:03.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:11:03.823+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.108 seconds
[2024-07-01T23:11:34.572+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:11:34.574+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:11:34.578+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:11:34.577+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:11:34.620+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:11:34.611+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:11:34.624+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:11:34.732+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.173 seconds
[2024-07-01T23:12:20.439+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:12:20.441+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:12:20.445+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:12:20.444+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:12:20.490+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:12:20.478+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:12:20.494+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:12:20.569+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.142 seconds
[2024-07-01T23:12:51.149+0000] {processor.py:161} INFO - Started process (PID=32) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:12:51.151+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:12:51.154+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:12:51.153+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:12:51.193+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:12:51.184+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:12:51.197+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:12:51.265+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.129 seconds
[2024-07-01T23:13:21.973+0000] {processor.py:161} INFO - Started process (PID=33) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:13:21.975+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:13:21.978+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:13:21.977+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:13:22.016+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:13:22.008+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:13:22.019+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:13:22.074+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.111 seconds
[2024-07-01T23:13:52.368+0000] {processor.py:161} INFO - Started process (PID=34) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:13:52.370+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:13:52.373+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:13:52.372+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:13:52.409+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:13:52.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:13:52.412+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:13:52.481+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.125 seconds
[2024-07-01T23:14:22.810+0000] {processor.py:161} INFO - Started process (PID=35) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:14:22.812+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:14:22.818+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:14:22.816+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:14:22.862+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:14:22.853+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:14:22.865+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:14:22.928+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.129 seconds
[2024-07-01T23:14:53.194+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:14:53.195+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:14:53.198+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:14:53.197+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:14:53.232+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:14:53.224+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:14:53.235+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:14:53.294+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.110 seconds
[2024-07-01T23:15:23.600+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:15:23.602+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-07-01T23:15:23.604+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:15:23.604+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:15:23.641+0000] {logging_mixin.py:188} INFO - [2024-07-01T23:15:23.632+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-07-01T23:15:23.645+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-07-01T23:15:23.704+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.119 seconds
