[2024-06-28T21:01:07.824+0000] {processor.py:161} INFO - Started process (PID=30) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:01:07.826+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:01:07.831+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:01:07.830+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:01:08.181+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:01:08.224+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.414 seconds
[2024-06-28T21:01:38.579+0000] {processor.py:161} INFO - Started process (PID=36) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:01:38.581+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:01:38.593+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:01:38.590+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:01:38.951+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:01:39.699+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 1.134 seconds
[2024-06-28T21:02:09.905+0000] {processor.py:161} INFO - Started process (PID=37) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:02:09.907+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:02:09.911+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:02:09.910+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:02:10.153+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:02:10.185+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.292 seconds
[2024-06-28T21:02:41.356+0000] {processor.py:161} INFO - Started process (PID=38) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:02:41.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:02:41.362+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:02:41.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:02:41.635+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:02:41.670+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.325 seconds
[2024-06-28T21:03:11.893+0000] {processor.py:161} INFO - Started process (PID=39) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:03:11.895+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:03:11.900+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:03:11.899+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:03:12.146+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:03:12.176+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.297 seconds
[2024-06-28T21:03:42.602+0000] {processor.py:161} INFO - Started process (PID=40) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:03:42.604+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:03:42.618+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:03:42.617+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:03:42.909+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:03:42.941+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.357 seconds
[2024-06-28T21:04:13.174+0000] {processor.py:161} INFO - Started process (PID=42) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:04:13.176+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:04:13.182+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:04:13.181+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:04:13.473+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:04:13.525+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.369 seconds
[2024-06-28T21:04:44.206+0000] {processor.py:161} INFO - Started process (PID=43) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:04:44.209+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:04:44.214+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:04:44.213+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:04:44.615+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:04:44.674+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.486 seconds
[2024-06-28T21:05:15.479+0000] {processor.py:161} INFO - Started process (PID=44) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:05:15.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:05:15.485+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:05:15.484+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:05:15.820+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:05:15.872+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.410 seconds
[2024-06-28T21:05:47.477+0000] {processor.py:161} INFO - Started process (PID=45) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:05:47.481+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:05:47.498+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:05:47.497+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:05:47.944+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:05:47.993+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.540 seconds
[2024-06-28T21:06:19.132+0000] {processor.py:161} INFO - Started process (PID=46) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:19.134+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:06:19.138+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:06:19.137+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:19.647+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:19.692+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.575 seconds
[2024-06-28T21:06:42.838+0000] {processor.py:161} INFO - Started process (PID=47) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:42.840+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:06:42.843+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:06:42.843+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:42.884+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:06:42.877+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 18, in <module>
    with DAG('stream-dag', schedule='@daily', default_args=default_args):
         ^^^
NameError: name 'DAG' is not defined
[2024-06-28T21:06:42.888+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:42.950+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.123 seconds
[2024-06-28T21:06:50.330+0000] {processor.py:161} INFO - Started process (PID=48) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:50.333+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:06:50.338+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:06:50.337+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:50.497+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:06:50.469+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:06:50.505+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:06:50.642+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.327 seconds
[2024-06-28T21:07:21.706+0000] {processor.py:161} INFO - Started process (PID=49) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:07:21.708+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:07:21.712+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:07:21.711+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:07:21.752+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:07:21.743+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:07:21.756+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:07:21.814+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.120 seconds
[2024-06-28T21:07:52.897+0000] {processor.py:161} INFO - Started process (PID=50) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:07:52.899+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:07:52.903+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:07:52.902+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:07:52.939+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:07:52.931+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:07:52.941+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:07:53.002+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.116 seconds
[2024-06-28T21:08:24.080+0000] {processor.py:161} INFO - Started process (PID=51) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:08:24.082+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:08:24.086+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:08:24.085+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:08:24.131+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:08:24.122+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:08:24.135+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:08:24.245+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.175 seconds
[2024-06-28T21:08:55.094+0000] {processor.py:161} INFO - Started process (PID=52) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:08:55.096+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:08:55.099+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:08:55.099+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:08:55.140+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:08:55.131+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:08:55.144+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:08:55.209+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.129 seconds
[2024-06-28T21:09:25.356+0000] {processor.py:161} INFO - Started process (PID=53) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:09:25.358+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:09:25.362+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:09:25.361+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:09:25.411+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:09:25.401+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:09:25.415+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:09:25.496+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.156 seconds
[2024-06-28T21:09:55.813+0000] {processor.py:161} INFO - Started process (PID=54) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:09:55.817+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:09:55.822+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:09:55.821+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:09:55.898+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:09:55.885+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:09:55.904+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:09:56.045+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.258 seconds
[2024-06-28T21:10:27.224+0000] {processor.py:161} INFO - Started process (PID=55) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:10:27.226+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:10:27.230+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:10:27.229+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:10:27.272+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:10:27.264+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:10:27.274+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:10:27.336+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.128 seconds
[2024-06-28T21:10:31.247+0000] {processor.py:161} INFO - Started process (PID=56) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:10:31.251+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:10:31.256+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:10:31.255+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:10:31.340+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:10:31.328+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:10:31.344+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:10:31.432+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.199 seconds
[2024-06-28T21:11:01.740+0000] {processor.py:161} INFO - Started process (PID=57) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:01.744+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:11:01.749+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:01.747+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:01.806+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:01.794+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:11:01.812+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:01.906+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.184 seconds
[2024-06-28T21:11:32.158+0000] {processor.py:161} INFO - Started process (PID=58) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:32.160+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:11:32.167+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:32.165+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:32.238+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:32.220+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:11:32.244+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:32.386+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.250 seconds
[2024-06-28T21:11:38.782+0000] {processor.py:161} INFO - Started process (PID=59) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:38.783+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:11:38.787+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:38.786+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:38.839+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:38.832+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:11:38.841+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:38.892+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.122 seconds
[2024-06-28T21:11:42.931+0000] {processor.py:161} INFO - Started process (PID=60) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:42.936+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:11:42.941+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:42.940+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:43.065+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:11:43.051+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:11:43.071+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:11:43.435+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.529 seconds
[2024-06-28T21:12:13.913+0000] {processor.py:161} INFO - Started process (PID=61) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:13.916+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:12:13.920+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:13.919+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:13.953+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:13.945+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 19, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:12:13.956+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:14.029+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.128 seconds
[2024-06-28T21:12:29.588+0000] {processor.py:161} INFO - Started process (PID=62) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:29.591+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:12:29.595+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:29.594+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:29.675+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:29.658+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 20, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:12:29.680+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:29.777+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.208 seconds
[2024-06-28T21:12:36.891+0000] {processor.py:161} INFO - Started process (PID=63) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:36.893+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:12:36.897+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:36.896+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:36.951+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:36.943+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 20, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:12:36.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:37.013+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.132 seconds
[2024-06-28T21:12:43.952+0000] {processor.py:161} INFO - Started process (PID=64) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:43.954+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:12:43.958+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:43.957+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:44.032+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:12:44.019+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 20, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:12:44.036+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:12:44.108+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.167 seconds
[2024-06-28T21:13:14.957+0000] {processor.py:161} INFO - Started process (PID=65) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:13:14.958+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:13:14.961+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:13:14.960+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:13:14.997+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:13:14.988+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 20, in <module>
    t1 = PythonOperator('get_data', python_callable=get_data, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:13:14.999+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:13:15.053+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.106 seconds
[2024-06-28T21:13:42.695+0000] {processor.py:161} INFO - Started process (PID=66) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:13:42.697+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:13:42.701+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:13:42.700+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:13:42.783+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:13:42.771+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', )
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:13:42.787+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:13:42.871+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.191 seconds
[2024-06-28T21:14:09.693+0000] {processor.py:161} INFO - Started process (PID=67) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:09.694+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:14:09.697+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:14:09.697+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:09.761+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:14:09.753+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:14:09.765+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:09.825+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.141 seconds
[2024-06-28T21:14:21.617+0000] {processor.py:161} INFO - Started process (PID=68) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:21.620+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:14:21.632+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:14:21.631+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:21.907+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:14:21.863+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:14:21.940+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:22.161+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.573 seconds
[2024-06-28T21:14:52.920+0000] {processor.py:161} INFO - Started process (PID=69) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:52.922+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:14:52.926+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:14:52.925+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:52.971+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:14:52.960+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:14:52.975+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:14:53.049+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.145 seconds
[2024-06-28T21:15:23.211+0000] {processor.py:161} INFO - Started process (PID=70) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:15:23.213+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:15:23.215+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:15:23.215+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:15:23.258+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:15:23.248+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:15:23.261+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:15:23.333+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.131 seconds
[2024-06-28T21:15:53.912+0000] {processor.py:161} INFO - Started process (PID=71) to work on /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:15:53.914+0000] {processor.py:830} INFO - Processing file /opt/airflow/dags/kafka-stream.py for tasks to queue
[2024-06-28T21:15:53.917+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:15:53.916+0000] {dagbag.py:545} INFO - Filling up the DagBag from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:15:53.951+0000] {logging_mixin.py:188} INFO - [2024-06-28T21:15:53.943+0000] {dagbag.py:355} ERROR - Failed to import: /opt/airflow/dags/kafka-stream.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/dagbag.py", line 351, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/opt/airflow/dags/kafka-stream.py", line 22, in <module>
    t1 = PythonOperator('welcome-_log', python_callable=print_welcome, dag=dag)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.11/site-packages/airflow/models/baseoperator.py", line 443, in apply_defaults
    raise AirflowException("Use keyword arguments when initializing operators")
airflow.exceptions.AirflowException: Use keyword arguments when initializing operators
[2024-06-28T21:15:53.954+0000] {processor.py:842} WARNING - No viable dags retrieved from /opt/airflow/dags/kafka-stream.py
[2024-06-28T21:15:54.038+0000] {processor.py:183} INFO - Processing /opt/airflow/dags/kafka-stream.py took 0.138 seconds
